### ISSUE TITLE
Set up front-end database

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/discover#55]
We will be storing all information on user's devices. This means that we need to use browser's storage options. In the past we used `dexie.js` which worked pretty well. What do you think @abdhalees? Have you done anything like this before?

**Comment by abdhalees** [comment]
@ivanmauricio I'm going to investigate both these options: 
1- react-redux-dexie https://github.com/dfahlander/Dexie.js/tree/master/samples/react-redux
2- redux-ofline https://github.com/redux-offline/redux-offline

**Comment by abdhalees** [comment]
useful to read: 
https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0

**Comment by abdhalees** [comment]
@ivanmauricio 
Do we need a front-end database since we're going to use redux? 
whatever the answer is we need to persist the redux store, one way to do that is by using [redux-persist](https://github.com/rt2zz/redux-persist) which will store the redux object in the browser it's also possible to do that using dexiejs as shown here [react-redux-dexie example](https://github.com/dfahlander/Dexie.js/tree/master/samples/react-redux) but then we need to update dexie database by code on every update to redux unlike `redux-persist` which is a middleware. The biggest difference is that `dexie` uses IndexedDB while `redux-persist` uses one of these stores [store engines](https://github.com/rt2zz/redux-persist#storage-engines) 

`redux-offline` seems to be a good solution here, it makes it easy to add offline support to redux when using the network and making requests and most importantly [it uses `redux-persist` by default](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/read-resilience.md) and gives you several options to [configure](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md) 

So:
1- we'll still need to use `redux-offline` or any other package for offline support.
2- It's possible to use both `redux-offline` and `dexiejs` 
The question is do we need both? or `redux-offline` alone is enough? does it matter if the data is stored in `IndexedDB` or `LocalStorage`? does `dexiejs` has any additional features we will use?

**Comment by ivanmauricio** [comment]
@abdhalees 
Thanks for your research on this. Just read the article that you linked to and `redux-offline` seems like a great library, with good docs and a good community. I am happy to go with `redux-offline` with default `redux-persist`.
